# Generated by Django 5.0.4 on 2024-04-16 18:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('abbreviation', models.CharField(default='CODE', max_length=250)),
                ('about', models.TextField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('number', models.PositiveIntegerField(null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('certification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='notes.certification')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'ordering': ['certification', 'number'],
                'unique_together': {('certification', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('content', models.TextField()),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='notes.domain')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'ordering': ['updated', 'name'],
                'unique_together': {('name', 'domain')},
            },
        ),
    ]
