# Generated by Django 5.0.4 on 2024-04-21 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_certification_course_alter_course_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['course', 'number'], 'verbose_name': 'Domain', 'verbose_name_plural': 'Domains'},
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='certification',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together={('course', 'number')},
        ),
    ]
