# Generated by Django 4.2.14 on 2024-08-19 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_domain_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='entry_images')),
            ],
            options={
                'verbose_name': 'Entry Image',
                'verbose_name_plural': 'Entry Images',
                'ordering': ['updated'],
            },
        ),
    ]
