# Generated by Django 5.0.4 on 2024-04-17 05:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0002_remove_domain_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('definition', models.TextField()),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.certification')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'ordering': ['name'],
                'unique_together': {('certification', 'name')},
            },
        ),
    ]
