# Generated by Django 5.0.4 on 2024-04-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_alter_term_certification'),
        ('notes', '0004_alter_domain_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='certification',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('course', 'name')},
        ),
    ]
