# Generated by Django 4.2.11 on 2024-04-19 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_rename_event_myevent_alter_myevent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myevent',
            options={'ordering': ['event_on'], 'verbose_name': 'My Event', 'verbose_name_plural': 'My Events'},
        ),
    ]
