# Generated by Django 5.0.4 on 2024-04-19 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_myevent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myevent',
            options={'ordering': ['start_time'], 'verbose_name': 'My Event', 'verbose_name_plural': 'My Events'},
        ),
        migrations.RemoveField(
            model_name='myevent',
            name='event_on',
        ),
        migrations.AddField(
            model_name='myevent',
            name='end_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='myevent',
            name='start_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
