# Generated by Django 5.0.4 on 2024-04-19 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_myevent_options_remove_myevent_event_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myevent',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='myevent',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
