# Generated by Django 5.0.4 on 2024-04-19 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_myevent_end_time_alter_myevent_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myevent',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
