# Generated by Django 5.0.4 on 2024-04-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_myevent_added_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myevent',
            name='end_time',
        ),
    ]
